# Pandas

In [1]:
import pandas as pd

In [6]:
data = pd.Series([0.25,0.5,0.75,1.0],index=['a','b','c','d'])

In [7]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [8]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [10]:
print(pd.__version__)

0.25.1


In [11]:
A = pd.Series([2,3,4,5],index=['a','b','c','d'])

In [12]:
A.values

array([2, 3, 4, 5], dtype=int64)

In [13]:
type(A.values)

numpy.ndarray

In [14]:
type(A)

pandas.core.series.Series

In [15]:
A.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [16]:
A['a']

2

In [17]:
A['a':'c'] #Here the final index is included

a    2
b    3
c    4
dtype: int64

In [19]:
grads_dict = {'A':4, 'B':3.5, 'C':3, 'D':2.5}
grads = pd.Series(grads_dict)

In [20]:
grads.values

array([4. , 3.5, 3. , 2.5])

In [21]:
marks_dict = {'A':85,'B':75,'C':65,'D':55}
marks = pd.Series(marks_dict)

In [22]:
marks

A    85
B    75
C    65
D    55
dtype: int64

In [23]:
marks['A']

85

In [24]:
marks[0:2]

A    85
B    75
dtype: int64

In [25]:
grads_dict = {'A':4,'B':3.5,'C':3,'D':2.5}
grads = pd.Series(grads_dict)

In [26]:
grads.values

array([4. , 3.5, 3. , 2.5])

In [28]:
marks_dict = {'A':85,'B':75,'C':65,'D':55} 
marks = pd.Series(marks_dict)

In [29]:
marks

A    85
B    75
C    65
D    55
dtype: int64

In [30]:
marks['A']

85

In [31]:
marks[0:2]

A    85
B    75
dtype: int64

A,B,C,D are explicit indices

0,1,2,... are implicit indices

In [32]:
marks

A    85
B    75
C    65
D    55
dtype: int64

In [34]:
grads

A    4.0
B    3.5
C    3.0
D    2.5
dtype: float64

In [35]:
D = pd.DataFrame({'Marks':marks,'Grades':grads})

In [36]:
D

Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [37]:
D.T

A     B     C     D
Marks   85.0  75.0  65.0  55.0
Grades   4.0   3.5   3.0   2.5

In [38]:
D

Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [39]:
D.values

array([[85. ,  4. ],
       [75. ,  3.5],
       [65. ,  3. ],
       [55. ,  2.5]])

In [40]:
D.values[2,0]

65.0

In [41]:
D.columns

Index(['Marks', 'Grades'], dtype='object')

In [42]:
D

Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [44]:
D['ScaledMarks'] = 100*(D['Marks']/90)

In [45]:
D

Marks  Grades  ScaledMarks
A     85     4.0    94.444444
B     75     3.5    83.333333
C     65     3.0    72.222222
D     55     2.5    61.111111

In [46]:
del D['ScaledMarks']

In [47]:
D

Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [48]:
G = D[D['Marks']>70]

In [49]:
G

Marks  Grades
A     85     4.0
B     75     3.5

# NaN

In [52]:
A = pd.DataFrame([{'a':1,'b':4},{'b':-3,'c':9}])

In [53]:
A

a  b    c
0  1.0  4  NaN
1  NaN -3  9.0

In [55]:
A.fillna(0) #Fill NaN with zero. We can fill it with any other number

a  b    c
0  1.0  4  0.0
1  0.0 -3  9.0

In [56]:
A.dropna?

# Indexing

In [57]:
data = pd.Series(['a','b','c'],index = [1,3,5])

data[1] #explicit index, use loc instead

data[1:3] #implicit index, use iloc instead

In [59]:
A = pd.Series(['a','b','c'],index = [1,3,5])

In [60]:
A[1]

'a'

In [62]:
A[1:3]  #Implicit indices

3    b
5    c
dtype: object

In [65]:
A.loc[1:3] #Explicit indices

1    a
3    b
dtype: object

In [67]:
A.iloc[1:3] #Implicit indices

3    b
5    c
dtype: object

In [68]:
D 

Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [69]:
D.iloc[2,:]

Marks     65.0
Grades     3.0
Name: C, dtype: float64

In [70]:
D.iloc[::-1,:]

Marks  Grades
D     55     2.5
C     65     3.0
B     75     3.5
A     85     4.0